name: rusttest
language: rust

image:
  name: rust/latest
  rebuild: false
  workdir: config/Dockerfile
  copy: ./rust

test:
  activate: true
  command: "cargo test"

compilation:
  activate: true
  command: "cargo build --release"
  path: "/usr/src/myapp/target/release/"
  file: "rust"

deploy:
  activate: false

lint:
  activate: true
  command: "cargo fmt -- --check"

delete:
  activate: false